# -*- coding: utf-8 -*-
"""read_csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C92ZKDfNsW0zOdRcHKoQtwCKCPuohPSn
"""

import csv

def read_csv(file_path):
    with open(file_path, mode='r') as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)

# Test the function
read_csv('/content/username.csv')  # Uncomment and replace with your CSV file